-- Creation of raw tables

CREATE TABLE "raw_departures" (
  "id"           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "collected_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "station_id"   TEXT,
  "raw_json"     jsonb
);

CREATE TABLE "raw_arrivals" (
  "id"           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "collected_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "station_id"   TEXT,
  "raw_json"     jsonb
);

CREATE TABLE "raw_disruptions" (
  "id"           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "collected_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "raw_json"     jsonb
);

-- Creation of structured tables

CREATE TABLE stop_areas (
  area_id   TEXT NOT NULL PRIMARY KEY,
  name TEXT NOT NULL,
  lon       DOUBLE PRECISION NOT NULL,
  lat       DOUBLE PRECISION NOT NULL
);

CREATE TABLE stations (
  station_id   TEXT NOT NULL PRIMARY KEY,
  station_name TEXT NOT NULL,
  area_id      TEXT NOT NULL REFERENCES stop_areas(area_id),
  lon          DOUBLE PRECISION NOT NULL,
  lat          DOUBLE PRECISION NOT NULL
);

CREATE TABLE lines (
  line_id   TEXT NOT NULL PRIMARY KEY,
  line_name TEXT NOT NULL
);

CREATE TABLE networks (
  network_id   TEXT NOT NULL PRIMARY KEY,
  network_name TEXT NOT NULL
);

CREATE TABLE disruptions (
  id         TEXT NOT NULL PRIMARY KEY,
  status     TEXT NOT NULL,
  severity   TEXT NOT NULL,
  message    TEXT
);

CREATE TABLE disrupted_stations (
  disruption_id TEXT NOT NULL REFERENCES disruptions(id) ON DELETE CASCADE,
  station_id      TEXT NOT NULL REFERENCES stations(station_id) ON DELETE CASCADE,
  PRIMARY KEY (disruption_id, station_id)
);

CREATE TABLE disrupted_objects (
  disruption_id TEXT NOT NULL REFERENCES disruptions(id) ON DELETE CASCADE,
  object_id       TEXT NOT NULL,
  embedded_type   TEXT NOT NULL,
  physical_mode   TEXT,
  PRIMARY KEY (disruption_id, object_id)
);

CREATE TABLE disruption_periods (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  disruption_id TEXT NOT NULL REFERENCES disruptions(id) ON DELETE CASCADE,
  period_start    TIMESTAMPTZ,
  period_end      TIMESTAMPTZ
);

CREATE TABLE flux (
  vehicle_journey_id TEXT NOT NULL,
  station_id         TEXT NOT NULL REFERENCES stations(station_id) ON DELETE CASCADE,
  origin_id          TEXT NOT NULL REFERENCES stop_areas(area_id),
  terminus_id        TEXT NOT NULL REFERENCES stop_areas(area_id),
  base_time_in       TIMESTAMPTZ,
  time_in            TIMESTAMPTZ,
  base_time_out      TIMESTAMPTZ,
  time_out           TIMESTAMPTZ,
  line_id            TEXT NOT NULL REFERENCES lines(line_id),
  network_id         TEXT NOT NULL REFERENCES networks(network_id),
  physical_mode      TEXT NOT NULL,
  PRIMARY KEY (vehicle_journey_id, station_id)
);


-- Indexes to make requests faster
CREATE UNIQUE INDEX disruption_periods_dedup ON disruption_periods(disruption_id, COALESCE(period_start, '-infinity'::timestamptz), COALESCE(period_end, 'infinity'::timestamptz));
CREATE INDEX disrupted_stations_disruption_id ON disrupted_stations(disruption_id);
CREATE INDEX disrupted_stations_station_id ON disrupted_stations(station_id);
CREATE INDEX flux_station_id ON flux(station_id);
CREATE INDEX flux_line_id ON flux(line_id);
CREATE INDEX flux_network_id ON flux(network_id);
CREATE INDEX flux_physical_mode_id ON flux(physical_mode);
